---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-core-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-core
  template:
    metadata:
      labels:
        app: app-core
    spec:
      containers:
        - name: app-core
          image: event_testing/app_core:latest
          ports:
            - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-peripheral-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-peripheral
  template:
    metadata:
      labels:
        app: app-peripheral
    spec:
      containers:
        - name: app-peripheral
          image: event_testing/app_peripheral:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: app-core-service
spec:
  selector:
    app: app-core
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 8000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "rabbitmq-with-management-command-enabled"
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672
            - name: amqp
              protocol: TCP
              containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "rabbit_user"
            - name: RABBITMQ_DEFAULT_PASS
              value: "rabbit_password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: celery-worker
          ports:
            - containerPort: 8000
